In [61]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [62]:
import numpy as np

In [63]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [64]:
a = [1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [65]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [66]:
l = [[1,2,3],[4,5,6],[7,8,9]]

mat = np.array(l)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [68]:
print(np.zeros(6))
print(np.ones(6))

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


In [69]:
print(np.zeros((2,3)))


[[0. 0. 0.]
 [0. 0. 0.]]


In [70]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [71]:
print(np.linspace(1,2,5))

[1.   1.25 1.5  1.75 2.  ]


In [72]:
np.random.rand(5)

array([0.98578975, 0.97267392, 0.83574529, 0.73911085, 0.71999002])

In [73]:
np.random.randn(5)

array([-0.2743515 ,  1.31332016, -0.52987484,  1.86471298, -0.45368544])

In [74]:
np.random.randint(100)

19

In [75]:
m = [[1,2,3],[4,5,6],[7,8,9]]

ma = np.array(m)
print(ma)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
ma.shape

(3, 3)

In [77]:
ma.size

9

In [78]:
ma.dtype

dtype('int64')

In [79]:
ma.min()

np.int64(1)

In [80]:
ma.max()

np.int64(9)

In [81]:
ma.sum()

np.int64(45)

In [82]:
np.sum(ma,axis = 1)

array([ 6, 15, 24])

In [83]:
ma.mean()

np.float64(5.0)

In [84]:
ma.std()

np.float64(2.581988897471611)

In [85]:
np.argmax(ma)

np.int64(8)

In [86]:
np.argmin(ma)

np.int64(0)

In [87]:
a = np.arange(1,31)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [88]:
a.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])