In [31]:
import numpy as np

In [32]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
print(arr[6])

17


In [34]:
print(arr[:])
print(arr[2:6])
print(arr[0:21:2])

[11 12 13 14 15 16 17 18 19 20]
[13 14 15 16]
[11 13 15 17 19]


In [35]:
arr1 = np.arange(1,31).reshape(6,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [36]:
print(arr1[1])
print(arr1[0,0])

[ 6  7  8  9 10]
1


In [37]:
slice = arr1[0:2,1 : 3]
print(slice)

[[2 3]
 [7 8]]


In [38]:
bool_index = arr1 % 2 == 0
bool_index

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])